### ISSUE TITLE
read statusCode from err.statusCode?

### ISSUE THREAD

**Issue by yorkie** [expressjs/errorhandler#11]
Hi This is a question like the title, the loopback framework is using `err.statusCode` to expose the http status code. And I did know the preprocessor would address the issue.

However, I just think why not supporting statusCode from the error object, the node core is using this name, so should we use this as well?

Thanks !!!

**Comment by dougwilson** [comment]
Can you point me to where the "node core" is using this field?

**Comment by yorkie** [comment]
wow~ thanks for such quick reply, for your question, i mean here: https://iojs.org/api/http.html#http_response_statuscode

**Comment by dougwilson** [comment]
OK I thought you meant node core was using err.statusCode somewhere

**Comment by yorkie** [comment]
In fact I meant the loopback is using the `statusCode`, that is my pain for this issue, check this: https://github.com/strongloop/loopback/blob/master/common/models/user.js#L192, @dougwilson how do you think supporting statusCode as well? if lgtm, i'm glad to submit a pr for you :)

**Comment by dougwilson** [comment]
I know it's used there. You just said node core as well, so I was confused. You can make a PR, yes, but it'll sit for a month or so, because some of these modules are still tied to Express 3 release schedules until it goes away.

Basically feel free because I was going to do it anyway, but don't expect a release soon :)
