### ISSUE TITLE
More readable output formats

### ISSUE THREAD

**Issue by rightaway** [expressjs/errorhandler#14]
If doing `throw {a: 'a', b: [ { c: 'c' } ]}` you get the output

```
    { a: 'a', b: [ { c: 'c' } ] }
```

It would be more readable, especially for larger objects, if it were pretty-printed instead of on one line and no indentation like above.

If doing `throw Error({a: 'a', b: [ { c: 'c' } ]})`, the first line of the output before the stack trace is

```
Error: [object Object]
```

Which is fine, but it would also be very useful to output, elsewhere on the page, a pretty-printed output of the object passed in to the `Error` object. Otherwise you would have to use a debugger or insert console.log commands in your code to get at the object.

**Comment by dougwilson** [comment]
Hi @rightaway !

> It would be more readable, especially for larger objects, if it were pretty-printed instead of on one line and no indentation like above.

We already do this, as far as I know. The string we provide is simply the output of `util.inspect` from Node.js core (https://nodejs.org/api/util.html#util_util_inspect_object_options). The exact string you are going to get back will of course depend on the version of Node.js you are running on, but the current versions will automatically detect how long the output is and include line breaks as appropriate. You can see this effect with the following:
```
$ node -pe 'require("util").inspect({a: "a", b: [ { c: "c" } ]})'
{ a: 'a', b: [ { c: 'c' } ] }

$ node -pe 'require("util").inspect({a: "a", b: [ { c: "c" }, { d: "d" }, { e: "e" }, { f: "f" } ]})'
{ a: 'a',
  b: [ { c: 'c' }, { d: 'd' }, { e: 'e' }, { f: 'f' } ] }

$ node -pe 'require("util").inspect({a: "a", b: [ { c: "c" }, { d: "d" }, { e: "e" }, { f: "f" }, { g: "g" }, { h: "h" } ]})'
{ a: 'a',
  b:
   [ { c: 'c' },
     { d: 'd' },
     { e: 'e' },
     { f: 'f' },
     { g: 'g' },
     { h: 'h' } ] }
```

As for your second question, regarding `throw Error({a: 'a', b: [ { c: 'c' } ]})`, there is nothing we can do about this. It's actually how JavaScript works. The first argument to `Error` is `message`, which is converted to a string during the `Error` object construction (done by `String("throw Error({a: 'a', b: [ { c: 'c' } ]})")`, which results in `[object Object]`). The actual object is no longer available for us to display to you because of this.
