### ISSUE TITLE
 'errorhandler@^1.5.0' is not in the npm registry

### ISSUE THREAD

**Issue by sandupa-govinena** [expressjs/errorhandler#25]
NPM cannot resolve the package from the registry.

npm ERR! 404 Not Found - GET https://registry.npmjs.org/errorhandler

**Comment by dougwilson** [comment]
Hi @sandupa-govinena sorry you're having problems. You'll need to contact npm support for help if their registry is having issue for you: https://npm.community/

I am able to load the URL you provided above without a 404, but due to geographical location, you may be ending up on different npm servers than I; npm support is best situated to assist in this situation.

**Comment by gbl-peter** [comment]
NPM support has closed the issue as Resolved, however errorhandler is still 404'ing.

https://status.npmjs.org/

**Comment by dougwilson** [comment]
Thanks for the update. It sounds like we just have to wait for npm to correct the issue, as it doesn't sound like there is any action I can take to resolve it.
